

import { InventoryItem, Transaction, Category, Location, TransactionType } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_linen', name: '布草', color: '#8b5cf6' }, // Purple for Linens
  { id: 'cat_amenities', name: '客房一次性用品', color: '#10b981' }, // Green for Amenities
  { id: 'cat_bulk', name: '大桶洗护', color: '#f59e0b' }, // Orange for Bulk liquids
  { id: 'cat_cleaning', name: '清洁用品', color: '#3b82f6' }, // Blue generic
];

export const INITIAL_LOCATIONS: Location[] = [
  { id: 'loc_main', name: '总库房' },
  { id: 'loc_floor1', name: '1楼布草间' },
  { id: 'loc_floor2', name: '2楼布草间' },
  { id: 'loc_hk', name: '客房部' },
];

const now = new Date().toISOString();

export const INITIAL_ITEMS: InventoryItem[] = [
  // --- 布草类 (Linens) ---
  {
    id: 'lin_001',
    name: '1.8米被套 (275*250)',
    category: '布草',
    location: '总库房',
    quantity: 16,
    unit: '条',
    minStockLevel: 10,
    price: 125.00,
    lastUpdated: now,
  },
  {
    id: 'lin_002',
    name: '1.8米床单 (280*300)',
    category: '布草',
    location: '总库房',
    quantity: 24,
    unit: '条',
    minStockLevel: 15,
    price: 98.00,
    lastUpdated: now,
  },
  {
    id: 'lin_003',
    name: '1.2米床单 (220*300)',
    category: '布草',
    location: '总库房',
    quantity: 22,
    unit: '条',
    minStockLevel: 15,
    price: 75.00,
    lastUpdated: now,
  },
  {
    id: 'lin_004',
    name: '1.2米被套 (215*250)',
    category: '布草',
    location: '总库房',
    quantity: 24,
    unit: '条',
    minStockLevel: 15,
    price: 105.00,
    lastUpdated: now,
  },
  {
    id: 'lin_005',
    name: '1.35米被套 (230*250)',
    category: '布草',
    location: '1楼布草间',
    quantity: 66,
    unit: '条',
    minStockLevel: 30,
    price: 115.00,
    lastUpdated: now,
  },
  {
    id: 'lin_006',
    name: '1.35米床单 (235*300)',
    category: '布草',
    location: '1楼布草间',
    quantity: 62,
    unit: '条',
    minStockLevel: 30,
    price: 88.00,
    lastUpdated: now,
  },
  {
    id: 'lin_007',
    name: '枕套 (61*91)',
    category: '布草',
    location: '总库房',
    quantity: 262,
    unit: '个',
    minStockLevel: 100,
    price: 25.00,
    lastUpdated: now,
  },
  {
    id: 'lin_008',
    name: '内枕套',
    category: '布草',
    location: '总库房',
    quantity: 300,
    unit: '个',
    minStockLevel: 100,
    price: 18.00,
    lastUpdated: now,
  },
  {
    id: 'lin_009',
    name: '浴巾',
    category: '布草',
    location: '2楼布草间',
    quantity: 130,
    unit: '条',
    minStockLevel: 50,
    price: 45.00,
    lastUpdated: now,
  },
  {
    id: 'lin_010',
    name: '毛巾',
    category: '布草',
    location: '2楼布草间',
    quantity: 120,
    unit: '条',
    minStockLevel: 50,
    price: 18.00,
    lastUpdated: now,
  },
  {
    id: 'lin_011',
    name: '地巾',
    category: '布草',
    location: '2楼布草间',
    quantity: 65,
    unit: '条',
    minStockLevel: 30,
    price: 32.00,
    lastUpdated: now,
  },

  // --- 客房一次性用品 (Amenities) ---
  {
    id: 'amn_001',
    name: '拖鞋',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 17,
    unit: '包',
    minStockLevel: 5,
    price: 400.00,
    description: '大包*500双',
    lastUpdated: now,
  },
  {
    id: 'amn_002',
    name: '洗手液',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 96,
    unit: '瓶',
    minStockLevel: 20,
    price: 8.50,
    description: '库存: 2箱',
    lastUpdated: now,
  },
  {
    id: 'amn_003',
    name: '马桶套',
    category: '客房一次性用品',
    location: '客房部',
    quantity: 30,
    unit: '盒',
    minStockLevel: 10,
    price: 15.00,
    description: '3大包(每大包10盒)',
    lastUpdated: now,
  },
  {
    id: 'amn_004',
    name: '一次性纸杯',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 3,
    unit: '箱',
    minStockLevel: 2,
    price: 120.00,
    lastUpdated: now,
  },
  {
    id: 'amn_005',
    name: '护理包',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 1,
    unit: '箱',
    minStockLevel: 1,
    price: 180.00,
    lastUpdated: now,
  },
  {
    id: 'amn_006',
    name: '浴帽',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 1,
    unit: '箱',
    minStockLevel: 1,
    price: 150.00,
    lastUpdated: now,
  },
  {
    id: 'amn_007',
    name: '梳子',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 4,
    unit: '箱',
    minStockLevel: 2,
    price: 200.00,
    lastUpdated: now,
  },
  {
    id: 'amn_008',
    name: '牙具',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 8,
    unit: '箱',
    minStockLevel: 3,
    price: 350.00,
    description: '8箱 (黑白各4箱) *1000个',
    lastUpdated: now,
  },
  {
    id: 'amn_009',
    name: '沐浴液 (小瓶)',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 1,
    unit: '箱',
    minStockLevel: 1,
    price: 450.00,
    description: '小瓶 (500瓶一箱)',
    lastUpdated: now,
  },
  {
    id: 'amn_010',
    name: '洗发水 (小瓶)',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 1,
    unit: '箱',
    minStockLevel: 1,
    price: 450.00,
    description: '小瓶 (500瓶一箱)',
    lastUpdated: now,
  },
  {
    id: 'amn_011',
    name: '护发素 (小瓶)',
    category: '客房一次性用品',
    location: '总库房',
    quantity: 1,
    unit: '箱',
    minStockLevel: 1,
    price: 450.00,
    description: '小瓶 (500瓶一箱)',
    lastUpdated: now,
  },

  // --- 大桶洗护 (Bulk) ---
  {
    id: 'blk_001',
    name: '5L 沐浴液',
    category: '大桶洗护',
    location: '总库房',
    quantity: 2,
    unit: '箱',
    minStockLevel: 1,
    price: 180.00,
    description: '5L/桶 (一箱4桶)',
    lastUpdated: now,
  },
  {
    id: 'blk_002',
    name: '5L 洗发水',
    category: '大桶洗护',
    location: '总库房',
    quantity: 1,
    unit: '箱',
    minStockLevel: 1,
    price: 180.00,
    description: '5L/桶 (一箱4桶)',
    lastUpdated: now,
  },
  {
    id: 'blk_003',
    name: '5L 护发素',
    category: '大桶洗护',
    location: '总库房',
    quantity: 1,
    unit: '箱',
    minStockLevel: 1,
    price: 180.00,
    description: '5L/桶 (一箱4桶)',
    lastUpdated: now,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_demo_1',
    itemId: 'lin_001',
    itemName: '1.8米被套 (275*250)',
    type: TransactionType.INBOUND,
    quantity: 16,
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
    user: '采购部',
    notes: '月度补货',
  },
  {
    id: 'tx_demo_2',
    itemId: 'amn_001',
    itemName: '拖鞋',
    type: TransactionType.OUTBOUND,
    quantity: 1,
    timestamp: new Date(Date.now() - 86400000 * 1).toISOString(),
    user: '客房主管',
    notes: '领用1大包至楼层',
  },
];
